### ISSUE TITLE
iOS: pressing cancel doesn't stop scanning

### ISSUE THREAD

**Issue by jakolion** [mintware-de/flutter_barcode_reader#60]
This is my code:

```
String data = "";
try {
    data = await BarcodeScanner.scan();
} on PlatformException catch ( e ) {
    if ( e.code == BarcodeScanner.CameraAccessDenied ) {
        _log.warning( "camera permission not granted" );
        return;
    }
    else {
        _log.warning( "$e" );
        return;
    }
} on FormatException {
    // scan was canceled by user
    _log.info( "scan canceled by user" );
    return;
}
catch ( e ) {
    _log.warning( "$e" );
    return;
}
```

Pressing cancel when the camera is turned on, I expect the "FormatException". On Android this is working fine. On iOS, the flash is turned off, the camera screen is popped and the view is going back the the previous page as expected. But in the background the scanning is still active and the code above is still in line 3. When holding the phone over a QR code it is scanned successfully and the code above is continuing.

Tested with iOS 11.4 (15F79) on iPhone 5s and with iOS 12.1 (16B92) on iPhone 8.

**Comment by jakolion** [comment]
Fixed with the mentioned merge request #55 and release 0.0.8. Can be closed.

**Comment by lauraseidler** [comment]
@jakolion do you get the FormatException on iOS? For me the scanner now stops and disappears, but I get neither an exception (not even in the last general catch block), nor a result.

**Comment by jakolion** [comment]
> @jakolion do you get the FormatException on iOS? For me the scanner now stops and disappears, but I get neither an exception (not even in the last general catch block), nor a result.

You are describing the behavior I had before version 0.0.8. The scanner disappeared and the previous page was shown but it was still running in the background.
With release 0.0.8 it worked the same way as before and throws the FormatException when canceling.
https://pub.dartlang.org/packages/barcode_scan/versions/0.0.8

**Comment by lauraseidler** [comment]
> You are describing the behavior I had before version 0.0.8. The scanner disappeared and the previous page was shown but it was still running in the background.

Not quite - the scanner is off, as far as I can see, but I'm still not getting any Exception (or empty result). It feels like the Future is somehow not resolving at all (and I have 0.0.8).

**Comment by jakolion** [comment]
> Not quite - the scanner is off, as far as I can see, but I'm still not getting any Exception (or empty result). It feels like the Future is somehow not resolving at all (and I have 0.0.8).

After cancelling the scanner was still active in line 3 of my code above. There wasn't any result or exception as well. If you are really using version 0.0.8 then I don't have any idea. Currently it's working fine for me.

**Comment by theneedyguy** [comment]
I have the same issue. The app on iOS does not throw the format exception when I press cancel. Using 0.0.8 too.

**Comment by mdudek** [comment]
I'm facing same issue as @theneedyguy with version 0.0.8.

**Comment by ricpar11** [comment]
still having this error in version 1.0.0, any fix?

**Comment by JohanSnygg** [comment]
I have no way of testing this, but I may have a fix if someone could test it out and then commit it to the branch.

in the file **BarcodeScannerViewController.m** change the method "cancel" to:

**- (void)cancel {
    [self.delegate barcodeScannerViewController:self didFailWithErrorCode:@"USER_CANCELED"];
    [self dismissViewControllerAnimated:true completion:nil];
}**

and in **barcode_scan.dart** add:

**static const UserCancelled = 'USER_CANCELED';**

for use in exception handling around BarcodeScanner.scan();

Hope this helps

**Comment by duskmont** [comment]
I have the same issue when using 1.0.0

**Comment by ashkryab** [comment]
I have the same issue 1.0.0

**Comment by lookfirst** [comment]
@JohanSnygg That suggestion fails with an exception. Throws things into a debugger in xcode. =(

@matthewtsmith Could you please take a look at this issue?

**Comment by lookfirst** [comment]
Ok, I figured it out, something just started working after resetting my codebase:

Per instructions from @JohanSnygg above. This seems pretty obvious now... cancel is called, but nothing is returned, so the Future in Dart never completes...

```
- (void)cancel {
    [self.delegate barcodeScannerViewController:self didFailWithErrorCode:@"USER_CANCELED"];
    [self dismissViewControllerAnimated:true completion:nil];
}
```

Now we can check for the `PlatformException`:

```
class BarcodeScanner {
  static const CameraAccessDenied = 'PERMISSION_NOT_GRANTED';
  static const UserCanceled = 'USER_CANCELED';
  static const MethodChannel _channel =
      const MethodChannel('com.apptreesoftware.barcode_scan');
  static Future<String> scan() async => await _channel.invokeMethod('scan');
}
```

I think this was the final goodness, change to `copy` (Also fixes warning in xcode)...

```
@property(nonatomic, copy) FlutterResult result;
```

**Comment by victor5171** [comment]
Hello! Do you have any ideas when this fixed version will be published at Dart's Repository?

**Comment by lookfirst** [comment]
@victor5171 

```
  barcode_scan:
    git: https://github.com/apptreesoftware/flutter_barcode_reader
    ref: 39ecc57bc0eef7b0465c891d900d2fb1f34a2390
```

**Comment by devtronic** [comment]
@victor5171 A new version is available
